import uuid
from pathlib import Path
from typing import Protocol

from app.config import settings


class PhotoStorage(Protocol):
    """Where photo bytes live. Local disk now, an S3-compatible bucket later."""

    def save(self, data: bytes, extension: str) -> str:
        """Store the bytes and return an opaque key."""

    def read(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...


class LocalPhotoStorage:
    def __init__(self, root: str):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def save(self, data: bytes, extension: str) -> str:
        key = f"{uuid.uuid4().hex}.{extension}"
        (self.root / key).write_bytes(data)
        return key

    def read(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def _path(self, key: str) -> Path:
        # Keys are generated by save(); reject anything that could escape the root.
        if "/" in key or "\\" in key or key.startswith("."):
            raise FileNotFoundError(key)
        return self.root / key


def get_storage() -> PhotoStorage:
    return LocalPhotoStorage(settings.storage_dir)
